### ISSUE TITLE
Dear Merschformann, can this software simulate the charging of a robot?

### ISSUE THREAD

**Issue by Bellmint** [merschformann/RAWSim-O#13]
I've been working on a robotic charging strategy and wanted to see if RAWSim-O could do it.
Thank you very much.

**Comment by merschformann** [comment]
Hey @Bellmint ! 

Unfortunately, batteries are not considered. 

If you are up for it, you could implement it yourself. You would need to define another [robot state](https://github.com/merschformann/RAWSim-O/blob/main/RAWSimO.Core/Bots/BotStateType.cs) and then handle it in the [bot implementation](https://github.com/merschformann/RAWSim-O/blob/main/RAWSimO.Core/Bots/BotNormal.cs). Basically, track the battery level, update it according to the different actions the robot is doing and sending them to charge where the tasks are being generated whenever necessary (according to your strategy). For the strategy you could use a similar structure as it was used for the other controllers.

It's not trivial though, without knowing/understanding the codebase a little.

**Comment by Bellmint** [comment]
Thank you very much sir. @merschformann 
I am reading your papers and hope it will help. I will try to write the code myself. 
I hope to keep in touch with you in the future so that I can ask some questions.
Sorry for my poor English.

**Comment by merschformann** [comment]
No worries. And sure, feel free to ask questions. ☺️ 
I will close this for now.
