### ISSUE TITLE
 Cannot find the resource file: Mu-1000.xgenc

### ISSUE THREAD

**Issue by mojoee** [merschformann/RAWSim-O#7]
Dear Marius,

thank you for sharing this great research tool, the great tutorials and giving us insight into your research of RMFS. I was trying to run an experiment from the cli and was missing out the resource Mu-1000.xgenc. 

I was running the following from the command line: 

_D:\user\02_Projects\00_Kiva\RawSim2\RAWSim-O\RAWSimO.CLI\bin\x64\Debug\RAWSimO.CLI.exe 1-4-4-32-0.85.xlayo SimpleItem-Fill-200-200-86400.xsett PPFAR-TABalanced-SAActivateAll-ISEmptiest-PSNearest-RPDummy-OBPodMatching-RBSamePod-MMNoChange.xconf Results 1_

This results in the below error: 

Unhandled Exception: System.ArgumentException: Cannot find the resource file: Mu-1000.xgenc(Tried: D:\scratch\mmarius\research\awsimopt\resources\Wordlists,D:\scratch\mmarius\research\awsimopt\resources,D:\scratch\mmarius\research\awsimopt\repo\Material\Resources\Wordlists,D:\scratch\mmarius\research\awsimopt\repo\Material\Resources,D:\scratch\herbort\storage_eval\repo\Material\Resources\Wordlists,D:\scratch\herbort\storage_eval\repo\Material\Resources,Material\Resources\Wordlists,Material\Resources,repo\Material\Resources\Wordlists,repo\Material\Resources,..\..\..\Material\Resources\Wordlists,..\..\..\Material\Resources,..\..\..\..\Material\Resources\Wordlists,..\..\..\..\Material\Resources,Resources\Wordlists,Resources,Wordlists)
   at RAWSimO.Core.IO.IOHelper.FindResourceFile(String resourceFile, String instancePath) in D:\Moritz\02_Projects\00_Kiva\RawSim2\RAWSim-O\RAWSimO.Core\IO\IOHelper.cs:line 50
   at RAWSimO.Core.IO.InstanceIO.ReadInstance(String instancePath, String settingConfigPath, String controlConfigPath, Boolean overrideVisualizationAttached, Boolean visualizationOnly, Action`1 logAction) in D:\Moritz\02_Projects\00_Kiva\RawSim2\RAWSim-O\RAWSimO.Core\IO\InstanceIO.cs:line 85
   at RAWSimO.CLI.Program.Main(String[] args) in D:\Moritz\02_Projects\00_Kiva\RawSim2\RAWSim-O\RAWSimO.CLI\Program.cs:line 166

It seems like I am missing some resource. However, I cloned this github repo and reproduced the video tutorials that you shared. The normal simulation is running. Do you know how to fix this ? Any help is highly appreciated ! Thank you

**Comment by mojoee** [comment]
Thank you for your swift and helpful response! I created the Mu-1000.xgenc file as you described and the simulation can be run smoothly from the cli.  🙏 

Hope my research project will go this smooth as well 🥼 🌝

**Comment by merschformann** [comment]
Great! I keep my fingers crossed for your project. :relaxed: 

FWIW: Unfortunately, there is not much documentation in general, but you can find some descriptions of above mentioned parameters [here](https://github.com/merschformann/RAWSim-O/wiki/Order-and-inventory-configuration). Maybe that can be of some help too.
